name: mac
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        VNC_USER_PASSWORD: ${{ secrets.VNC_USER_PASSWORD }}
        VNC_PASSWORD: ${{ secrets.VNC_PASSWORD }}
      run: sh configure.sh "$VNC_USER_PASSWORD" "$VNC_PASSWORD" "$NGROK_AUTH_TOKEN"
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: but wait, there's more
      run: git clone https://github.com/novnc/noVNC.git
    - name: init noVNC
      run: cd noVNC && ./utils/launch.sh --listen 8080 --vnc localhost:5900 &
    - name: ngrok HTML5 access
      run: ngrok http 8080 &
    - name: you can go by way of http to...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Persistance
      uses: actions/cache@v2
      env:
        cache-name: save
      with:
        path: ~/
        key: windows
    - name: heres the thing
      run: echo "*$(date)*"$'\n'"macOS VM \`$(hostname)\` is online, VNC is available now at \`$(curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url' | sed 's .\{7\}  ' | tr -d \")\`"$'\n'"*Your password to the* \`VNC User\` *account is* \`$(echo $USERPASSWORD)\`"$'\n'"Your VNC Basic Auth password is \`$(echo $VNCPASSWORD)\`"
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
